##
## QLoRA 사용을 위한 도커
## 참고: https://huggingface.co/blog/4bit-transformers-bitsandbytes

FROM nvcr.io/nvidia/pytorch:23.05-py3

ARG UID=
ARG USER_NAME=


ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /workspace

SHELL ["/bin/bash", "-c"]

RUN apt-get update && apt-get install -y --no-install-recommends sudo && \
    apt-get install -y ffmpeg && \
    apt-get install -y git-lfs && \
    rm -rf /var/lib/apt/lists/*

# Create a user
RUN adduser $USER_NAME -u $UID --quiet --gecos "" --disabled-password && \
    echo "$USER_NAME ALL=(root) NOPASSWD:ALL" > /etc/sudoers.d/$USER_NAME && \
    chmod 0440 /etc/sudoers.d/$USER_NAME

RUN pip install -U datasets evaluate openai safetensors sentencepiece bitsandbytes deepspeed pillow timm scikit-learn librosa jiwer gradio openpyxl XlsxWriter jupyterlab==3.5.3 ipywebrtc ipywidgets && \
    pip install -U git+https://github.com/huggingface/transformers.git && \
    pip install -U git+https://github.com/huggingface/peft.git && \
    pip install -U git+https://github.com/huggingface/accelerate.git
