##
## PEFT를 제대로 사용하기 위한 도커 (PEFT, QLoRA, AWQ, GPTQ ...)
## v1.2.dev (2023-11-30)
## 주요 패키지
## - 음성 인식 관련, 트랜스포머, 디퓨저 등

FROM pytorch/pytorch:2.1.0-cuda12.1-cudnn8-devel

ARG UID=
ARG USER_NAME=


ENV DEBIAN_FRONTEND=noninteractive

ENV CUDA_HOME=/usr/local/cuda

WORKDIR /workspace

SHELL ["/bin/bash", "-c"]

RUN apt-get update && apt-get install -y --no-install-recommends sudo && \
    apt-get install -y ffmpeg && \
    apt-get install -y git-lfs && \
    apt-get install -y gdb && \
    apt-get install wget && \
    rm -rf /var/lib/apt/lists/*

# Create a user
RUN adduser $USER_NAME -u $UID --quiet --gecos "" --disabled-password && \
    echo "$USER_NAME ALL=(root) NOPASSWD:ALL" > /etc/sudoers.d/$USER_NAME && \
    chmod 0440 /etc/sudoers.d/$USER_NAME

RUN pip install transformers diffusers["torch"] peft accelerate optimum auto-gptq trl seqeval safetensors sentencepiece bitsandbytes deepspeed datasets evaluate && \
    pip install -U openai tiktoken pillow timm pandas scipy scikit-learn librosa jiwer gradio openpyxl XlsxWriter jupyterlab>=3.5.3 ipywebrtc ipywidgets gekko wandb einops