##
## MLOPS v1.5
## v1.4.dev (2025-05-25)
## 주요 패키지
## - 언어 모델, 음성 인식 관련, 트랜스포머, 디퓨저 등

FROM pytorch/pytorch:2.7.0-cuda12.8-cudnn9-devel
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

ARG UID=
ARG USER_NAME=

ENV DEBIAN_FRONTEND=noninteractive

ENV CUDA_HOME=/usr/local/cuda

WORKDIR /workspace

SHELL ["/bin/bash", "-c"]

RUN apt update && apt install -y --no-install-recommends sudo && \
    apt install -y ffmpeg && \
    apt install -y git-lfs && \
    apt install -y gdb && \
    apt install -y screen curl vim wget && \
    rm -rf /var/lib/apt/lists/*

# Create a user
RUN adduser $USER_NAME -u $UID --quiet --gecos "" --disabled-password && \
    echo "$USER_NAME ALL=(root) NOPASSWD:ALL" > /etc/sudoers.d/$USER_NAME && \
    chmod 0440 /etc/sudoers.d/$USER_NAME


RUN pip install transformers accelerate diffusers peft datasets evaluate webdataset ftfy optimum autoawq auto-gptq trl gcsfs seqeval safetensors sentencepiece bitsandbytes deepspeed wandb einops unsloth && \
    pip install google-genai openai anthropic tiktoken pillow timm pandas scipy scikit-learn librosa jiwer gradio openpyxl XlsxWriter jupyterlab ipywebrtc ipywidgets gekko && \
    pip install flash-attn --no-build-isolation && \
    pip install pandas-ta python-binance